---
server:
  port: 9090
  contextPath: /ticket-catalog
datasource:
  sampleapp:
    url: jdbc:postgresql://localhost:5432/tickets
    username: postgres
    password: hdty389ktol
    driverClassName: org.postgresql.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

